default:
  image: mirror.central-x.com/compiler:jdk17
  tags:
    - docker

stages:
  - build
  - test
  - lint
  - deploy

# 编译测试
project:build:
  stage: build
  script:
    - mvn clean compile

# 单元测试
project:unit-test:
  stage: test
  script:
    - mvn verify
  artifacts:
    when: always
    expire_in: 30 days
    reports:
      junit:
        - central-*/target/surefire-reports/TEST-*.xml
        - central-*/target/failsafe-reports/TEST-*.xml
        - central-starters/central-*/target/surefire-reports/TEST-*.xml
        - central-starters/central-*/target/failsafe-reports/TEST-*.xml

# 使用 GitLab Pages 功能托管代码质量报告
pages:
  stage: lint
  image:
    name: jetbrains/qodana-jvm-community:2023.1
    entrypoint: [""]
  script:
    - qodana --save-report --results-dir=$CI_PROJECT_DIR/public --report-dir=$CI_PROJECT_DIR/public
  artifacts:
    expose_as: 'Lint report'
    paths:
      - public

# 发布到 Maven 仓库
project:deploy:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^*.x$/
    - if: $CI_COMMIT_TAG =~ /^*.RELEASE$/
  script:
    - mvn -s .ci/settings.xml clean deploy
